# Generated by Django 4.2.13 on 2024-05-23 14:52

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_landingpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", wagtail.fields.RichTextField(blank=True)),
                ("location", models.CharField(max_length=255)),
                ("image_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
